# Generated by Django 5.2.17 on 2026-09-23 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetState',
            fields=[
                ('key', models.CharField(default='main', max_length=30, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField(default='2026-10-01')),
                ('revision', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('format', models.CharField(max_length=20)),
                ('duration_hours', models.FloatField()),
                ('mandatory', models.BooleanField(default=False)),
                ('target_roles', models.JSONField(default=list)),
                ('target_grades', models.JSONField(default=list)),
                ('develops_skills', models.JSONField(default=list)),
                ('prerequisites', models.JSONField(default=dict)),
                ('upcoming_sessions', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
                ('manager_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField()),
                ('tenure_months', models.PositiveIntegerField()),
                ('work_format', models.CharField(max_length=20)),
                ('preferred_language', models.CharField(max_length=5)),
                ('career_goal', models.JSONField(blank=True, null=True)),
                ('skills', models.JSONField(default=dict)),
                ('last_review_date', models.DateField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quest.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
                ('required_skills', models.JSONField(default=dict)),
                ('critical_skills', models.JSONField(default=list)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'grade'), name='unique_role_grade')],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('record_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('completion_pct', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assigned_by', models.CharField(max_length=20)),
                ('request_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='quest.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='quest.event')),
            ],
            options={
                'ordering': ['date', 'record_id'],
                'indexes': [models.Index(fields=['employee', 'status', 'date'], name='quest_parti_employe_d855f7_idx')],
            },
        ),
    ]
