# Generated by Django 5.2.17 on 2026-09-23 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('files', models.JSONField()),
                ('preview', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='quest.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.event')),
                ('participation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_item', to='quest.participation')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'event'), name='unique_employee_plan_event'), models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'in_progress', 'completed', 'cancelled'])), name='valid_plan_status')],
            },
        ),
    ]
