# Generated by Django 5.2.17 on 2026-09-23 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_existing_demo_completions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.JSONField()),
                ('current_level', models.PositiveSmallIntegerField()),
                ('required_level', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ожидает HR'), ('proposed', 'Практика подготовлена'), ('completed', 'Результат подтверждён'), ('closed', 'Закрыт с ответом')], default='open', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PracticeBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('deliverable', models.TextField()),
                ('criteria', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('artifact_url', models.URLField(blank=True, max_length=1000)),
                ('criteria', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('changes_requested', 'Нужна доработка'), ('approved', 'Подтверждено')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('checked_criteria', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-attempt'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='developmentplanitem',
            name='valid_plan_status',
        ),
        migrations.AddField(
            model_name='event',
            name='for_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_events', to='quest.employee'),
        ),
        migrations.AlterField(
            model_name='developmentplanitem',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('submitted', 'На проверке'), ('needs_revision', 'На доработке'), ('completed', 'Завершено'), ('cancelled', 'Убрано из плана')], default='planned', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='developmentplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'in_progress', 'submitted', 'needs_revision', 'completed', 'cancelled'])), name='valid_plan_status'),
        ),
        migrations.AddField(
            model_name='developmentrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_requests', to='quest.employee'),
        ),
        migrations.AddField(
            model_name='developmentrequest',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='development_request', to='quest.event'),
        ),
        migrations.AddField(
            model_name='developmentrequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developmentrequest',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.skill'),
        ),
        migrations.AddField(
            model_name='practicebrief',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practicebrief',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_brief', to='quest.event'),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='plan_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quest.developmentplanitem'),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='developmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'proposed'])), fields=('employee', 'skill'), name='one_active_development_request'),
        ),
        migrations.AddConstraint(
            model_name='worksubmission',
            constraint=models.UniqueConstraint(fields=('plan_item', 'attempt'), name='unique_submission_attempt'),
        ),
        migrations.AddConstraint(
            model_name='worksubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('plan_item',), name='one_pending_submission'),
        ),
    ]
